apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "metabase.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- template "labels" . }}
data:
  {{- if .Values.log4jProperties }}
  log4j.properties:
{{ toYaml .Values.log4jProperties | indent 4}}
  {{- end}}
