apiVersion: v1
kind: Secret
metadata:
  name: {{ template "metabase.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- template "labels" . }}
type: Opaque
data:
  MB_DB_TYPE: {{ .Values.database.type }}
  {{- if and (ne (.Values.database.type | lower) "h2") }}
    {{- if .Values.database.encryptionKey }}
  MB_ENCRYPTION_SECRET_KEY: {{ .Values.database.encryptionKey | b64enc | quote }}
    {{- end }}
    {{- if .Values.database.connectionURI }}
  MB_DB_CONNECTION_URI: {{ .Values.database.connectionURI | b64enc | quote }}
    {{- else }}
  MB_DB_HOST: {{ .Values.database.host | quote }}
  MB_DB_PORT: {{ .Values.database.port | quote }}
  MB_DB_DBNAME: {{ .Values.database.dbname | quote }}
  MB_DB_USER: {{ .Values.database.username | b64enc | quote }}
  MB_DB_PASS: {{ .Values.database.password | b64enc | quote }}
    {{- end }}
  {{- end }}