{{- if .Values.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "metabase.fullname" . }}-ssl
  namespace: {{ .Release.Namespace }}
  labels:
    {{- template "labels" . }}
type: Opaque
data:
  MB_JETTY_SSL: true
  MB_JETTY_SSL_Port: {{ .Values.ssl.port | quote }}
  MB_JETTY_SSL_Keystore: {{ .Values.ssl.keystore | b64enc | quote }}
  MB_JETTY_SSL_Keystore_Password: {{ .Values.ssl.keyStorePassword | b64enc | quote }}
{{- end }}